### ISSUE TITLE
Parameter "startIndex"

### ISSUE THREAD

**Issue by CiberBot13** [djkaty/Il2CppInspector#96]
I'm trying to get a game dump but when I put the apk it returns the following error: "Index was out of range. Must be non negative and lessthan the size of the colection. (Parameter 'StartIndex')

**Comment by djkaty** [comment]
Please attach your il2cpp binary and global-metadata.dat so I can take a look when I have some time, thanks!

**Comment by CiberBot13** [comment]
[lib+mtd.zip](https://github.com/djkaty/Il2CppInspector/files/5453193/lib%2Bmtd.zip)

**Comment by djkaty** [comment]
Thank you, I've downloaded the files. There is quite a backlog right now (of several weeks) but I will look at it as soon as I have the opportunity. Thanks!

**Comment by CiberBot13** [comment]
thanks i'm waiting

**Comment by djkaty** [comment]
This binary uses a form of striped XOR encryption. I've been working on a solution for the last couple of hours, will hopefully have something for you in the next couple of days 🙂

**Comment by djkaty** [comment]
This issue should be resolved in https://github.com/djkaty/Il2CppInspector/commit/231ea09b763ccf3e23e6425bb32aac1753cf36b9 - please re-open the issue if you still have trouble. Thanks for the report!

**Comment by Colonel-Lee** [comment]
Same error still occured in latest release version 2021.1. Binary and metadata are as follow:
[global-metadata.zip](https://github.com/djkaty/Il2CppInspector/files/8596123/global-metadata.zip)
[libil2cpp.zip](https://github.com/djkaty/Il2CppInspector/files/8596124/libil2cpp.zip)
